### ISSUE TITLE
ERROR: Invalid policy while using ReadOnlyAccess managed Policy

### ISSUE THREAD

**Issue by saiprasanthrajavarapu** [awslabs/aws-cloudformation-iam-policy-validator#23]
I am using cfn-policy-validator to validate an UserRole and it does have managed ReadOnlyAccess policy attached to the role. I am seeing following error while running cfn-policy-validator.    
`2022-10-17 12:19:49,470 - cfn-policy-validator - INFO - Validating identity policy for SampleRole with name ReadOnlyAccess
Traceback (most recent call last):
  File "/Library/Python/3.10/lib/python/site-packages/cfn_policy_validator/main.py", line 129, in main
    args.func(args)
  File "/Library/Python/3.10/lib/python/site-packages/cfn_policy_validator/main.py", line 32, in validate_from_cli
    report = validator.validate(parser_output, arguments.ignore_finding, arguments.treat_as_blocking, arguments.allowed_external_principals)
  File "/Library/Python/3.10/lib/python/site-packages/cfn_policy_validator/validation/validator.py", line 26, in validate
    findings = validate_parser_output(parser_output)
  File "/Library/Python/3.10/lib/python/site-packages/cfn_policy_validator/validation/validator.py", line 39, in validate_parser_output
    validator.validate_roles(parser_output.Roles)
  File "/Library/Python/3.10/lib/python/site-packages/cfn_policy_validator/validation/validator.py", line 103, in validate_roles
    response = self.client.validate_policy(
  File "//Library/Python/3.10/lib/python/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/3.10/lib/python/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ValidatePolicy operation: InvalidPolicy
ERROR: Unexpected error occurred. An error occurred (ValidationException) when calling the ValidatePolicy operation: InvalidPolicy
`

**Comment by mluttrell** [comment]
This should be fixed in v0.0.17 that was just pushed.  Please let me know if you're still seeing an issue!

The fix will make it so that AWS managed policies that are too large for the ValidatePolicy API are not passed to it.  If the policy exceeds the limit and it's not an AWS managed policy, the validator will insert an error finding.

**Comment by saiprasanthrajavarapu** [comment]
thanks for quick turn around on this issue @mluttrell . I am able validate with ReadOnlyAccess managed policy
