### ISSUE TITLE
`cfn-policy-validator parse` command fails if there are no AWS credentials configured

### ISSUE THREAD

**Issue by Veetaha** [awslabs/aws-cloudformation-iam-policy-validator#46]
The following script that makes sure `parse` doesn't get any AWS creds fails

```bash
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_DEFAULT_REGION
unset AWS_REGION
unset AWS_PROFILE
cfn-policy-validator parse --region us-east-1 --template-path template.json
```

```
Traceback (most recent call last):
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/cfn_policy_validator/main.py", line 252, in main
    validate_credentials(args.region)
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/cfn_policy_validator/parameters.py", line 68, in validate_credentials
    sts_client.get_caller_identity()
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/signers.py", line 199, in sign
    auth.add_auth(request)
  File "/home/veetaha/work/elastio/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
ERROR: Unexpected error occurred. Unable to locate credentials
```

**Comment by Veetaha** [comment]
NVM, policy validator needs access to AWS to resolve SSM params for example, even though I don't use them in my template
